language: go

env:
  - GO111MODULE=on

go:
  - "1.x"
  - master

os:
  - linux
  - osx
  - windows

matrix:
  exclude:
    # Doesn't seem to work - see
    # https://travis-ci.com/houseabsolute/omegasort/jobs/224739813
    go: master
    os: windows
  include:
    env:
      - NAME="lint checking'
      - GO111MODULE=on
    go: "1.x"
    os: linux
    install:
      - ./dev/bin/install-dev-tools.sh
      - export PATH=$PATH:./bin

    script:
      - ./bin/precious lint -a

script:
  - go test -v ./...
