[commands.golangci-lint]
type = "lint"
include = "**/*.go"
exclude = [
    "internal/ip/**/*.go",
    "internal/posixpath/**/*.go",
    "internal/winpath/**/*.go",
]
run_mode = "root"
chdir = true
cmd = [
    "golangci-lint",
    "run",
    "-c",
    "$PRECIOUS_ROOT/golangci-lint.yml",
    "--skip-dirs", "internal/ip",
    "--skip-dirs", "internal/posixpath",
    "--skip-dirs", "internal/winpath",
]
env = { "FAIL_ON_WARNINGS" = "1" }
ok_exit_codes = [0]
lint_failure_exit_codes = [1]

[commands.goimports]
type = "tidy"
include = "**/*.go"
cmd = ["goimports", "-w"]
ok_exit_codes = [0]
