[commands.golangci-lint]
type = "lint"
include = "**/*.go"
exclude = [
    "internal/ip/**/*.go",
    "internal/posixpath/**/*.go",
    "internal/winpath/**/*.go",
]
run_mode = "dirs"
cmd = [
    "golangci-lint",
    "run",
    "-c",
    "$PRECIOUS_ROOT/golangci-lint.yml",
    "--allow-parallel-runners",
]
env = { "FAIL_ON_WARNINGS" = "1" }
ok_exit_codes = [0]
lint_failure_exit_codes = [1]

[commands.goimports]
type = "tidy"
include = "**/*.go"
cmd = [
    "golangci-lint",
    "run",
    "--fix",
    "--disable-all",
    "--enable", "goimports",
    "--allow-parallel-runners",
]
ok_exit_codes = [0]

[commands.check-go-mod]
type = "lint"
include = "**/*.go"
run_mode = "root"
chdir = true
cmd = ["$PRECIOUS_ROOT/dev/bin/check-go-mod.sh"]
ok_exit_codes = [0]
lint_failure_exit_codes = [1]
