[commands.golangci-lint]
type = "lint"
include = "**/*.go"
exclude = [
    "internal/ip/**/*.go",
    "internal/posixpath/**/*.go",
    "internal/winpath/**/*.go",
]
on_dir = true
run_once = true
chdir = true
cmd = [
    "golangci-lint",
    "run",
    "-c",
    "$PRECIOUS_ROOT/golangci-lint.yml",
    "--skip-dirs", "internal/ip",
    "--skip-dirs", "internal/posixpath",
    "--skip-dirs", "internal/winpath",
]
ok_exit_codes = [0]
lint_failure_exit_codes = [1]

[commands.check-go-mod]
type = "lint"
include = "**/*.go"
on_dir = true
run_once = true
chdir = true
cmd = ["$PRECIOUS_ROOT/dev/bin/check-go-mod.sh"]
expect_stderr = true
ok_exit_codes = [0]
lint_failure_exit_codes = [1]

[commands.goimports]
type = "tidy"
include = "**/*.go"
cmd = ["goimports", "-w"]
ok_exit_codes = [0]

