name: Linting

on: [push, pull_request]

env:
  CRATE_NAME: precious
  RUST_BACKTRACE: 1

jobs:
  lint:
    name: Check that code is lint clean using precious
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install dev tools
        run: |
          mkdir ~/bin
          PATH=$PATH:~/bin ./dev/bin/install-dev-tools.sh
      - name: Run precious
        run: |
          PATH=$PATH:~/bin precious lint -a
